# Generated by Django 4.2.7 on 2025-07-03 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_media/images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/videos/'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagereadstatus', to='chat.message'),
        ),
    ]
