# Generated by Django 4.2.7 on 2025-07-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Write something about yourself.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_online_status',
            field=models.BooleanField(default=True, help_text="Show when you're online."),
        ),
    ]
